routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('employees','EmployeesController');

Route::post('/email_available/check', 'EmployeesController@checkEmail')->name('email_available.check');

app/Employees.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Employees extends Model
{
	protected $table = 'employees';
	
	protected $fillable = [
        'name', 
        'email',
        'known_technologies',
        'joining_date',
        'file_upload',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeesController.php
<?php

namespace App\Http\Controllers;

use App\Employees;
use Illuminate\Http\Request;
use DB;

class EmployeesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $employees = Employees::latest()->paginate(5);

        //echo json_encode($employees); exit;

        return view('employees.index',compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('employees.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'    =>  'required',
            'email'     =>  'required|email|unique:employees',
            'file_upload'     =>  'required',
            'joining_date' => 'required',
            'known_technologies' => 'required|min:3'
        ]);

        $file_upload = $request->file('file_upload');

        $new_name = rand() . '.' . $file_upload->getClientOriginalExtension();
        $file_upload->move(public_path('images'), $new_name);

        $employees = new Employees();

        $employees->name = $request->name;
        $employees->email = $request->email;
        $imp = implode(", ", (array) $request->known_technologies);       

        $employees->known_technologies = $imp;
        $employees->joining_date = $request->joining_date;
        $employees->file_upload = $new_name;

       
        $employees->save();        

        return redirect('employees')->with('success', 'Employees Added successfully.');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employees  $employees
     * @return \Illuminate\Http\Response
     */
    public function show(Employees $employees,$id)

    {
        $data = Employees::findOrFail($id);
        return view('employees.show',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employees  $employees
     * @return \Illuminate\Http\Response
     */
    public function edit(Employees $employees, $id)
    {
        $data = Employees::findOrFail($id);

       
        return view('employees.edit',compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employees  $employees
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employees $employees, $id)
    {
        $image_name = $request->hidden_image;
        $image = $request->file('file_upload');

        if($image != '')
        {

        $request->validate([
            'name' => 'required',
            'email' => 'required',            
            'joining_date' => 'required',
            'known_technologies' => 'required|min:3'
        ]);
        $image_name = rand() . '.' . $image->getClientOriginalExtension();
        $image->move(public_path('images'), $image_name);
    }
    else{

        $request->validate([
                'name'    =>  'required',
                'email'     =>  'required',                
            'joining_date' => 'required',
            'known_technologies' => 'required|min:3'
            ]);

    }



    $form_data = array(
            'name'               =>   $request->name,
            'email'              =>   $request->email,
            'known_technologies' =>   implode(',',$request->known_technologies),
            'joining_date'       =>   $request->joining_date,
            'file_upload'        =>   $image_name
        );

    Employees::whereId($id)->update($form_data);

    return redirect('employees')->with('success', 'Employees Update successfully.');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employees  $employees
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Employees::findOrFail($id);
        $data->delete();

        return redirect('employees')->with('success', 'Employees successfully deleted.');
    }

    public function checkEmail(Request $request)
    {
     if($request->get('email'))
     {
      $email = $request->get('email');
      $data = DB::table("employees")
       ->where('email', $email)
       ->count();
      if($data > 0)
      {
       echo 'not_unique';
      }
      else
      {
       echo 'unique';
      }
     }
    }
}

resources/views/employees/create.blade.php
@extends('employees.layout')

@section('content')
@if($errors->any())
<div class="alert alert-danger">
 <ul>
  @foreach($errors->all() as $error)
  <li>{{ $error }}</li>
  @endforeach
 </ul>
</div>
@endif
<div align="right">
 <a href="{{ route('employees.index') }}" class="btn btn-default">Back</a>
</div>

<form method="post" action="{{ route('employees.store') }}" enctype="multipart/form-data" id="form">

 @csrf
 <div class="row">
  <div class="col-md-12">
  <div class="col-md-6">
 <div class="form-group">
  <label class="col-md-4 text-right">Employee Name</label>
  <div class="col-md-6">
   <input type="text" name="name" class="form-control"  placeholder="enter employee name" />
  </div>
 </div>
</div>
<div class="col-md-6">

 <div class="form-group">
  <label class="col-md-4 text-right">Employee Email</label>
  <div class="col-md-6">
   <input type="text" name="email" id="email" class="form-control" placeholder="enter employee email" />
   <span id="error_email"></span>
  </div>
 </div>
</div>
</div>
</div>

<br>
<br>


<div class="row">
  <div class="col-md-12">
  <div class="col-md-6">
 <div class="form-group">
  <label class="col-md-4 text-right">Joining Date</label>
  <div class="col-md-6">
   <input type="text" id="datepicker" name="joining_date" class="form-control" />
  </div>
 </div>
</div>
<div class="col-md-6">

 <div class="form-group">
  <label class="col-md-4 text-right">Upload a File</label>
  <div class="col-md-6">
   <input type="file" name="file_upload" />
  </div>
 </div>
</div>
</div>
</div>

<br>
<br>
<div class="row">
  <div class="col-md-12">
 <div class="form-group">
  <label class="col-md-4 text-right">Known Technologies</label>
  <div class="col-md-6">
   <input name="known_technologies[]" type="checkbox" value="1">PHP
  <input name="known_technologies[]" type="checkbox" value="2"> Javascript
  <input name="known_technologies[]" type="checkbox" value="3"> Ajax
  <input name="known_technologies[]" type="checkbox" value="4"> .NET
  <input name="known_technologies[]" type="checkbox" value="5"> Java
  </div>
 </div>    
  </div>
</div>
<br>
<br>

 <div class="form-group text-center">
  <input type="submit" name="add" class="btn btn-primary input-lg" value="Add" />
 </div>

</form>

<script>
$(document).ready(function(){

 $('#email').blur(function(){
  var error_email = '';
  var email = $('#email').val();
  //alert(email);
  var _token = $('input[name="_token"]').val();
  var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
  if(!filter.test(email))
  {    
   $('#error_email').html('<label class="text-danger">Invalid Email</label>');
   $('#email').addClass('has-error');
  
  }
  else
  {
   $.ajax({
    url:"{{ route('email_available.check') }}",
    method:"POST",
    data:{email:email, _token:_token},
    success:function(result)
    {
     if(result == 'unique')
     {
      $('#error_email').html('<label class="text-success">Email is correct</label>');
      $('#email').removeClass('has-error');
      
     }
     else
     {
      $('#error_email').html('<label class="text-danger">Email Is Already Taken</label>');
      $('#email').addClass('has-error');
      
     }
    }
   })
  }
 });
 
});
</script>

<script>
 
    $(document).ready(function () {
 
    $('#form').validate({ // initialize the plugin
        rules: {
            name: {
                required: true
            },
            email: {
                required: true,
                email: true
            },
            joining_date: {
                required: true,
                joining_date: true
            }, 
            file_upload: {
                required: true,
                file_upload:true
              },
            known_technologies: {
              required: true,
              known_technologies:true,
              min:3

            },         
            
        }
    });
});
</script>


@endsection

resources/views/employees/edit.blade.php
@extends('employees.layout')

@section('content')
            
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="pull-left">
                <h4>Edit Employees</h4>
            </div> 
            <div align="right">
                <a href="{{ route('employees.index') }}" class="btn btn-warning">Back</a>
            </div>
            <br />
     <form method="post" action="{{ route('employees.update', $data->id) }}" enctype="multipart/form-data" id ="form">
                @csrf
                @method('PATCH')
                
            <div class="row"> 
              

                <div class="col-sm-12">
                  <div class="col-sm-6">

      <div class="form-group">
       <label class="col-md-4 text-right">Name</label>
       <div class="col-md-8">
        <input type="text" name="name" value="{{ $data->name }}" class="form-control" />
       </div>
      </div>
    </div>
           
    <div class="col-sm-6">
      <div class="form-group">
       <label class="col-md-4 text-right">Email</label>
       <div class="col-md-6"> 
        <input type="text" name="email" value="{{ $data->email }}" class="form-control" />
       </div>
      </div>
    </div>
  </div>
</div>
      <br />
      <br />
      <br />
      <div class="row"> 
              

                <div class="col-sm-12">
                  <div class="col-sm-6">
       <div class="form-group">
       <label class="col-md-4 text-right">Joining Date</label>
       <div class="col-md-6">
        <input type="text" id="datepicker" name="joining_date" value="{{ $data->joining_date }}" class="form-control" />
       </div>
      </div>
    </div>
    <div class="col-sm-6">
       <div class="form-group">
       <label class="col-md-4 text-right">Uplode File</label>
       <div class="col-md-8">
        <input type="file" name="file_upload" />
        <a href="{{ URL::to('/') }}/images/{{ $data->file_upload }}" download="true">{{ $data->file_upload }}</a>
              
                        <input type="hidden" name="hidden_image" value="{{ $data->file_upload }}" />
       </div>
      </div>
      
    </div>
     
      
 </div>
 </div>
 </div> 
 <br />
      <br />
      <br />
      <div class="row">
        <div class="col-sm-12">
           <div class="form-group">
  <label class="col-md-4 text-right">Known Technologies</label>
  <div class="col-md-6">

       
   <input name="known_technologies[]" type="checkbox"  @php $conut =  $data->known_technologies; $count1 = explode(',', $conut); for($i=0;$i < count($count1); $i++){  if($count1[$i] == "1") {  echo 'checked'; } else { echo ''; }  } @endphp > PHP
  <input name="known_technologies[]" type="checkbox" value="2"  @php $conut =  $data->known_technologies; $count1 = explode(',', $conut); for($i=0;$i < count($count1); $i++){  if($count1[$i] == "2") {  echo 'checked'; } else { echo ''; } } @endphp > Javascript
  <input name="known_technologies[]" type="checkbox" value="3"  @php $conut =  $data->known_technologies; $count1 = explode(',', $conut); for($i=0;$i < count($count1); $i++){  if($count1[$i] == "3") {  echo 'checked'; } else { echo ''; } } @endphp > Ajax
  <input name="known_technologies[]" type="checkbox" value="4"  @php $conut =  $data->known_technologies; $count1 = explode(',', $conut); for($i=0;$i < count($count1); $i++){  if($count1[$i] == "4") {  echo 'checked'; } else { echo ''; } } @endphp > .NET
  <input name="known_technologies[]" type="checkbox" value="5"  @php $conut =  $data->known_technologies; $count1 = explode(',', $conut); for($i=0;$i < count($count1); $i++){  if($count1[$i] == "5") {  echo 'checked'; } else { echo ''; } } @endphp  > Java
  
    </div>
 </div>
</div>
</div>
     
      <br /><br /><br />
      <div class="form-group text-center">
       <input type="submit" name="edit" class="btn btn-primary " value="Update" />
       <a href="{{ route('employees.index') }}" class="btn btn-danger">Cancel</a>
      </div>
    </div>
 
     </form>
     <script>
$(document).ready(function(){

 $('#email').blur(function(){
  var error_email = '';
  var email = $('#email').val();
  //alert(email);
  var _token = $('input[name="_token"]').val();
  var filter = /^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
  if(!filter.test(email))
  {    
   $('#error_email').html('<label class="text-danger">Invalid Email</label>');
   $('#email').addClass('has-error');
  
  }
  else
  {
   $.ajax({
    url:"{{ route('email_available.check') }}",
    method:"POST",
    data:{email:email, _token:_token},
    success:function(result)
    {
     if(result == 'unique')
     {
      $('#error_email').html('<label class="text-success">Email is correct</label>');
      $('#email').removeClass('has-error');
      
     }
     else
     {
      $('#error_email').html('<label class="text-danger">Email Is Already Taken</label>');
      $('#email').addClass('has-error');
      
     }
    }
   })
  }
 });
 
});
</script>
     <script>
 
    $(document).ready(function () {
 
    $('#form').validate({ // initialize the plugin
        rules: {
            name: {
                required: true
            },
            email: {
                required: true,
                email: true
            },
            joining_date: {
                required: true,
                joining_date: true
            }, 
            file_upload: {
                required: true,
                file_upload:true
              },
            known_technologies: {
              required: true,
              known_technologies:true,
              min:3

            },         
            
        }
    });
});
</script>

@endsection

resources/views/employees/index.blade.php
@extends('employees.layout')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
           <!--  <div class="pull-left">
                <h2>Employees Management System</h2>
            </div> -->
            <br>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('employees.create') }}"> Create New Employees</a>
            </div>
        </div>
    </div>
    <br>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
           <th>SNO</th>
            <th>Name</th>
            <th>Email</th>
           
            <th>Joining Date</th>
            <th>Known Technologies</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($employees as $employee)
        <tr>
            <td>{{ $loop->iteration }}</td>
            <td>{{ $employee->name }}</td>
            <td>{{ $employee->email }}</td>           
            <td>{{ $employee->joining_date }}</td>
            <td> @php $conut =  $employee->known_technologies; $count1 = explode(',', $conut); for($i=0;$i < count($count1); $i++){  if($count1[$i] == "1") {  echo 'PHP,'; } else if ($count1[$i] == "2") { echo 'Javascript,'; } else if($count1[$i] == "3") { echo 'AJAX,'; } else if($count1[$i] == "4") { echo '.NET,'; } else if($count1[$i] == "5") { echo 'Java'; } else {}  } @endphp </td>
            <td>
                <form action="{{ route('employees.destroy',$employee->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('employees.show',$employee->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('employees.edit',$employee->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
{!! $employees->links() !!}
      
@endsection

resources/views/employees/layout.blade.php
<html>
 <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Employees Management System</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1' name='viewport'/>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha256-KM512VNnjElC30ehFwehXjx1YCHPiQkOPmqnrWtpccM=" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha256-rByPlHULObEjJ6XQxW/flG2r+22R5dKiAoef+aXWfik=" crossorigin="anonymous" />
  <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker({ dateFormat: 'yy-mm-dd' });
  } );
  </script>
  <style type="text/css">
    body {
  background-color: #FFFAFA;
}
  </style>
 </head>
 <body>
  <div class="container">    
     <br />
     <h3 align="center">Employees Management System</h3>
     <br />
     @yield('content')
    </div>
 </body>
</html>

resources/views/employees/show.blade.php
@extends('employees.layout')

@section('content')
            
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
             <div class="pull-left">
                <h4>Show Employees</h4>
            </div> 
            <div align="right">
                <a href="{{ route('employees.index') }}" class="btn btn-warning">Back</a>
            </div>
            <br />
<div class="container">
            <div class="row"> 
              

                <div class="col-sm-12">
                  <div class="col-sm-6"> 
                    <div class="form-group">
       <label class="col-md-4 ">Name</label>
       <div class="col-md-8">
        <input type="text" name="name" value="{{ $data->name }}" class="form-control"  readonly="" />
       </div>
      </div></div>
                   <div class="col-sm-6">
                       <div class="form-group">
       <label class="col-md-4 text-right">Email</label>
       <div class="col-md-6">
        <input type="text" name="email" value="{{ $data->email }}" class="form-control"  readonly=""/>
       </div>
      </div>
      </div>
                  
     </div>
   </div>

      <br />
      <br />
      <br />
       
      


    <div class="row"> 
      <div class="col-sm-12">
         <div class="col-sm-6">
           <div class="form-group">
       <label class="col-md-4 text-right">Joining Date</label>
       <div class="col-md-8">
        <input type="text" id="datepicker" name="joining_date" value="{{ $data->joining_date }}" class="form-control" readonly=""/>
       </div>
      </div>
         </div>
          <div class="col-sm-6">

 <div class="form-group">
       <label class="col-md-4 text-right">Uplode File</label>
       <div class="col-md-8">
        <input type="file" name="file_upload" readonly=""/>
        <a href="{{ URL::to('/') }}/images/{{ $data->file_upload }}" download="true">{{ $data->file_upload }}</a>
              
                        <input type="hidden" name="hidden_image" value="{{ $data->file_upload }}" />
       </div>
      </div>

           
          </div>
        
      </div>
    </div>
     <br />
      <br />
      <br />
       

    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
  <label class="col-sm-6 text-right">Known Technologies</label>
  <div class="col-md-6">


   
  <input name="known_technologies[]" type="checkbox" style="pointer-events:none;"  @php $conut =  $data->known_technologies; $count1 = explode(',', $conut); for($i=0;$i < count($count1); $i++){  if($count1[$i] == "1") {  echo 'checked'; } else { echo ''; }  } @endphp > PHP
  <input name="known_technologies[]" type="checkbox" value="2" style="pointer-events:none;" @php $conut =  $data->known_technologies; $count1 = explode(',', $conut); for($i=0;$i < count($count1); $i++){  if($count1[$i] == "2") {  echo 'checked'; } else { echo ''; } } @endphp > Javascript
  <input name="known_technologies[]" type="checkbox" value="3" style="pointer-events:none;"  @php $conut =  $data->known_technologies; $count1 = explode(',', $conut); for($i=0;$i < count($count1); $i++){  if($count1[$i] == "3") {  echo 'checked'; } else { echo ''; } } @endphp > Ajax
  <input name="known_technologies[]" type="checkbox" value="4" style="pointer-events:none;"  @php $conut =  $data->known_technologies; $count1 = explode(',', $conut); for($i=0;$i < count($count1); $i++){  if($count1[$i] == "4") {  echo 'checked'; } else { echo ''; } } @endphp > .NET
  <input name="known_technologies[]" type="checkbox" value="5" style="pointer-events:none;"  @php $conut =  $data->known_technologies; $count1 = explode(',', $conut); for($i=0;$i < count($count1); $i++){  if($count1[$i] == "5") {  echo 'checked'; } else { echo ''; } } @endphp  > Java

    </div>
 </div> 
    </div>
  </div>

             
            
     
    
      
 
     
      <br /><br /><br />
      <div class="form-group text-center">
        <a href="{{ route('employees.index') }}" class="btn btn-danger">Cancel</a>
      </div>
    </div>
  </div>

@endsection